### PR TITLE
Don't count peerDependencies towards bundle size

### LINKED ISSUE #6: Measuring a library seems to count its peer dependencies against it
If I clean tmp directory and run 
```
jsize react-dom@next
```

I get an error:

```
✖ 
ERROR in /private/var/folders/bj/0n3sjz9x6qq0s8s8tjfr30r5f42mg6/T/node_modules/react-dom/cjs/react-dom.production.min.js
Module not found: Error: Can't resolve 'react' in '/private/var/folders/bj/0n3sjz9x6qq0s8s8tjfr30r5f42mg6/T/node_modules/react-dom/cjs'
 @ /private/var/folders/bj/0n3sjz9x6qq0s8s8tjfr30r5f42mg6/T/node_modules/react-dom/cjs/react-dom.production.min.js 2:481-497
 @ /private/var/folders/bj/0n3sjz9x6qq0s8s8tjfr30r5f42mg6/T/node_modules/react-dom/index.js
```

As you see it tries to find `react`.

I understand you can’t *bundle* without it, but you probably shouldn’t try to. Since it's a peer dependency, it's unfair to count its size towards the main package. Measuring `react-dom` shouldn't count the size of `react` because the app will only include `react` once.

My intuition is that jsize should read `package.json`, and turn all `peerDependencies` into Webpack `externals` when bundling. Then the size is fair.

### PR DESCRIPTION
**Pull request by gaearon**
And generally fix builds for packages with peer dependencies.
Fixes https://github.com/antonmedv/jsize/issues/6.

### CODE REVIEW

**Comment by gaearon** [comment]
Rationale: users expected that app bundle size = app size alone + sum of sizes of direct dependencies. So we shouldn’t count them twice.

**Comment by gaearon** [comment]
(this is ready for review)

**Comment by DylanPiercey** [comment]
Great job on this PR, very clean. I was just working on the same thing but I'll merge yours instead :D. Thanks for your help today!

**Comment by gaearon** [comment]
Thanks! Feel free to refactor 😛 I'm not sure I fully understand the resolving logic so I did the simplest thing I could make work.

File: index.js [hunk 1]
```diff
@@ -65,15 +65,20 @@ function install (id) {
...
+ * @param {*} name - library folder name
+ * @param {*} file - entry point path relative to the library folder
  * @return {Promise<string>}
  */
-function build (file) {
+function build (name, file) {
   return new Promise((resolve, reject) => {
+    const entry = requireRelative.resolve(path.join(name, file), tmp);
+    const packageJson = requireRelative.resolve(path.join(name, 'package.json'), tmp);
+    const externals = Object.keys(require(packageJson).peerDependencies || {});
```
Comment (gaearon) [inline index.js:76]: I wonder if it's possible to declare the same thing in both `peerDeps` and regular `deps`. If it is then we should exclude things that are in regular `deps` from here. But I'm not sure npm would allow this anyway. Worth a check.

Comment (DylanPiercey) [reply index.js:76]: That's a good point. If I get some time later today I'll try to test that. I know it allows you to put both peer and dev but not sure if it gets translated into the installed package.json.

Anyways your solution is much cleaner than mine and I appreciate the PR's today 😀.
